const { registerAdminRoutes } = require("../routes/admin");
const { registerCheckoutRoutes } = require("../routes/checkout");
const { registerPublicApiRoutes } = require("../routes/public-api");
const { registerStorefrontRoutes } = require("../routes/storefront");
const { registerWebhookRoutes } = require("../routes/webhooks");

function registerWebhookEndpoints({
    app,
    db,
    providers,
    repositories,
    payments,
    text,
}) {
    registerWebhookRoutes({
        app,
        stripe: providers.stripe,
        env: providers.env,
        db,
        getOrderByProviderReference: repositories.getOrderByProviderReference,
        markOrderPaid: repositories.markOrderPaid,
        updateOrderStatus: repositories.updateOrderStatus,
        verifySwissBitcoinPayWebhook: payments.verifySwissBitcoinPayWebhook,
        normalizeText: text.normalizeText,
        mapSwissBitcoinPayStatus: payments.mapSwissBitcoinPayStatus,
    });
}

function registerPageRoutes({
    app,
    db,
    providers,
    http,
    text,
    money,
    forms,
    formatters,
    urls,
    publicProducts,
    cart,
    checkout,
    uploads,
    mail,
    payments,
    settings,
    products,
    admins,
    reviews,
    promos,
    dashboard,
    orders,
}) {
    registerPublicApiRoutes({
        app,
        db,
        stripe: providers.stripe,
        setPublicApiHeaders: publicProducts.setPublicApiHeaders,
        listPublishedProducts: products.listPublishedProducts,
        serializePublicProduct: publicProducts.serializePublicProduct,
        setCheckoutForm: checkout.setCheckoutForm,
        buildCheckoutDraft: checkout.buildCheckoutDraft,
        getCheckoutForm: checkout.getCheckoutForm,
        buildCart: cart.buildCart,
        setFlash: http.setFlash,
        saveSessionAndRedirect: http.saveSessionAndRedirect,
        clearStripeDraft: checkout.clearStripeDraft,
        getPromoCodeOutcome: checkout.getPromoCodeOutcome,
        createOrReuseStripeIntent: payments.createOrReuseStripeIntent,
        paymentState: payments.paymentState,
        normalizeText: text.normalizeText,
        validateCheckoutInput: checkout.validateCheckoutInput,
        requirePromoCodeOutcome: checkout.requirePromoCodeOutcome,
        getCheckoutPricing: checkout.getCheckoutPricing,
        getOrderByProviderReference: orders.getOrderByProviderReference,
        createOrder: orders.createOrder,
        notifyNewOrder: mail.notifyNewOrder,
        createOrderViewToken: payments.createOrderViewToken,
    });

    registerStorefrontRoutes({
        app,
        db,
        render: http.render,
        setFlash: http.setFlash,
        saveSessionAndRedirect: http.saveSessionAndRedirect,
        getSafeRedirectTarget: http.getSafeRedirectTarget,
        normalizeText: text.normalizeText,
        parseMoneyToCents: money.parseMoneyToCents,
        readSiteReviewInput: forms.readSiteReviewInput,
        readSelectedProductOptions: forms.readSelectedProductOptions,
        ensureAvailableProductQuantity: cart.ensureAvailableProductQuantity,
        upsertCartItem: cart.upsertCartItem,
        getCartItems: cart.getCartItems,
        makeCartItemKey: cart.makeCartItemKey,
        removeCartItem: cart.removeCartItem,
        productMetaDescription: publicProducts.productMetaDescription,
        productStructuredData: publicProducts.productStructuredData,
        organizationStructuredData: publicProducts.organizationStructuredData,
        listPublishedProducts: products.listPublishedProducts,
        listProductCategories: products.listProductCategories,
        listApprovedSiteReviews: reviews.listApprovedSiteReviews,
        getSiteReviewSummary: reviews.getSiteReviewSummary,
        createSiteReview: reviews.createSiteReview,
        getProductBySlug: products.getProductBySlug,
        getProductById: products.getProductById,
    });

    registerCheckoutRoutes({
        app,
        db,
        stripe: providers.stripe,
        SHIPPING_OPTIONS: formatters.SHIPPING_OPTIONS,
        render: http.render,
        setFlash: http.setFlash,
        saveSessionAndRedirect: http.saveSessionAndRedirect,
        buildCart: cart.buildCart,
        requirePromoCodeOutcome: checkout.requirePromoCodeOutcome,
        getCheckoutPricing: checkout.getCheckoutPricing,
        createOrder: orders.createOrder,
        getCheckoutForm: checkout.getCheckoutForm,
        getPromoCodeOutcome: checkout.getPromoCodeOutcome,
        paymentState: payments.paymentState,
        setCheckoutForm: checkout.setCheckoutForm,
        validateCheckout: forms.validateCheckout,
        createSwissBitcoinPayInvoice: payments.createSwissBitcoinPayInvoice,
        updateOrderProviderReference: orders.updateOrderProviderReference,
        clearCheckoutForm: checkout.clearCheckoutForm,
        setCartItems: cart.setCartItems,
        createOrderViewToken: payments.createOrderViewToken,
        sendNewOrderNotification: mail.sendNewOrderNotification,
        fetchSwissBitcoinPayInvoice: payments.fetchSwissBitcoinPayInvoice,
        mapSwissBitcoinPayStatus: payments.mapSwissBitcoinPayStatus,
        getOrderByProviderReference: orders.getOrderByProviderReference,
        markOrderPaid: orders.markOrderPaid,
        updateOrderStatus: orders.updateOrderStatus,
        getOrderByNumber: orders.getOrderByNumber,
        verifyOrderViewToken: payments.verifyOrderViewToken,
        clearStripeDraft: checkout.clearStripeDraft,
    });

    registerAdminRoutes({
        app,
        db,
        requireAdmin: http.requireAdmin,
        requireSuperadmin: http.requireSuperadmin,
        render: http.render,
        getViewHelpers: http.getViewHelpers,
        setFlash: http.setFlash,
        saveSessionAndRedirect: http.saveSessionAndRedirect,
        normalizeText: text.normalizeText,
        normalizeSingleLineText: text.normalizeSingleLineText,
        parseMoneyToCents: money.parseMoneyToCents,
        parseOptionalMoneyToCents: money.parseOptionalMoneyToCents,
        normalizeOrderDateTimeField: money.normalizeOrderDateTimeField,
        normalizePromoCode: checkout.normalizePromoCode,
        readAdminUserInput: forms.readAdminUserInput,
        readAdminAccountInput: forms.readAdminAccountInput,
        readPromoCodeInput: forms.readPromoCodeInput,
        getLoginRateLimitState: http.getLoginRateLimitState,
        registerLoginFailure: http.registerLoginFailure,
        clearLoginFailures: http.clearLoginFailures,
        getOrCreateCsrfToken: http.getOrCreateCsrfToken,
        readSelectedProductOptions: forms.readSelectedProductOptions,
        ensureAvailableProductQuantity: cart.ensureAvailableProductQuantity,
        validateRequestedServiceTags: cart.validateRequestedServiceTags,
        getProductUnitPriceCents: cart.getProductUnitPriceCents,
        getConfigurationAvailableQuantity: cart.getConfigurationAvailableQuantity,
        productCategoryList: publicProducts.productCategoryList,
        snapshotPackBundleItems: cart.snapshotPackBundleItems,
        getPromoCodeOutcome: checkout.getPromoCodeOutcome,
        getPromoCodeLabel: checkout.getPromoCodeLabel,
        getOrderContactSnapshot: orders.getOrderContactSnapshot,
        getOrderAdminData: orders.getOrderAdminData,
        buildOrderMailto: orders.buildOrderMailto,
        buildOrderEmailDraft: mail.buildOrderEmailDraft,
        isMailConfigured: mail.isMailConfigured,
        getMailConfigError: mail.getMailConfigError,
        sendStoreEmail: mail.sendStoreEmail,
        canEditOrderReceivedAmount: orders.canEditOrderReceivedAmount,
        readReceivedPaymentInput: orders.readReceivedPaymentInput,
        getOrderPaymentData: orders.getOrderPaymentData,
        settingsUploadUrl: uploads.settingsUploadUrl,
        withProductUploads: uploads.withProductUploads,
        withSettingsUpload: uploads.withSettingsUpload,
        productInputWithUploads: uploads.productInputWithUploads,
        buildProductFormState: uploads.buildProductFormState,
        baseUrl: urls.baseUrl,
        getOrderDocumentConfig: urls.getOrderDocumentConfig,
        getSettings: settings.getSettings,
        saveSettings: settings.saveSettings,
        createProduct: products.createProduct,
        updateProduct: products.updateProduct,
        deleteProduct: products.deleteProduct,
        listPacksContainingProduct: products.listPacksContainingProduct,
        listAdminProducts: products.listAdminProducts,
        listProductCategories: products.listProductCategories,
        listAdminCategories: products.listAdminCategories,
        deleteProductCategory: products.deleteProductCategory,
        getProductById: products.getProductById,
        getAdminByUsername: admins.getAdminByUsername,
        getAdminById: admins.getAdminById,
        listAdmins: admins.listAdmins,
        countAdminsByRole: admins.countAdminsByRole,
        createAdminUser: admins.createAdminUser,
        updateAdminUser: admins.updateAdminUser,
        deleteAdminUser: admins.deleteAdminUser,
        listPendingSiteReviews: reviews.listPendingSiteReviews,
        approveSiteReview: reviews.approveSiteReview,
        deleteSiteReview: reviews.deleteSiteReview,
        listPromoCodes: promos.listPromoCodes,
        getPromoCodeById: promos.getPromoCodeById,
        createPromoCodeRecord: promos.createPromoCodeRecord,
        updatePromoCodeRecord: promos.updatePromoCodeRecord,
        deletePromoCodeRecord: promos.deletePromoCodeRecord,
        getDashboardStats: dashboard.getDashboardStats,
        createOrder: orders.createOrder,
        getOrderById: orders.getOrderById,
        updateOrderRecord: orders.updateOrderRecord,
        markOrderPaid: orders.markOrderPaid,
        listRecentOrders: orders.listRecentOrders,
        listOrders: orders.listOrders,
        deleteOrder: orders.deleteOrder,
    });
}

function registerFallbackRoutes({
    app,
    setFlash,
    saveSessionAndRedirect,
}) {
    app.use((error, req, res, _next) => {
        console.error(error);

        if (req.currentAdmin) {
            setFlash(req, "error", `Erreur serveur : ${error.message}`);
            return saveSessionAndRedirect(req, res, req.get("referer") || "/admin");
        }

        return res.status(500).send("Internal Server Error");
    });

    app.use((req, res) => {
        res.status(404).render("not-found", { title: "Page introuvable" });
    });
}

module.exports = {
    registerWebhookEndpoints,
    registerPageRoutes,
    registerFallbackRoutes,
};
